### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by stefanor** [snowballstem/snowball-data#3]
Add a BSD license and contributor guidelines file, now, before there's a repeat of the issues raised in snowballstem/snowball#10 ?

There have been no contributions via GitHub, yet. Every contribution should have an implied BSD license.

**Comment by ojwb** [comment]
There's been one contribution via github: https://github.com/snowballstem/snowball-data/pull/2

However, that was from me so that one isn't a problem.

It's rare to make changes for this repo without corresponding changes to the main repo, but adding a licence here sounds like a good plan anyway.
