### ISSUE TITLE
Latin stemmer in branch fix-generate-dollar data not merged with branch master

### ISSUE THREAD

**Issue by GerritDeMeulder** [snowballstem/snowball-data#8]
Hi  @ojwb  Olly, 

It seems like a small oversight, but the voc.txt and output.txt files 
for the latin stemmer are only in the branch with tag [fix-generate-dollar](https://github.com/snowballstem/snowball-data/compare/master...fix-generate-dollar) data and not merged with branch master.

**Comment by ojwb** [comment]
That was deliberate (and I didn't merge the code of the Latin stemmer to the snowball repo either).

Unlike the other stemmers it returns two stems, so you can't call it like the others and use the resulting stem as a term for information retrieval - you'd need to special-case it and do something like indexing with both terms and retrieving with `(noun_stem OR verb_stem)`, so it didn't seem a good idea to merge it.  I was using it on the fix-generate-dollar branch as a test-case for the broken implementation of $ on a string for all the target languages except C.

If having the Latin stemmer in libstemer is something people actually want we can certainly look at how best to do that.

**Comment by ojwb** [comment]
No followup from submitter in nearly 6 months, so closing.

I'm happy to discuss how best to merge the Latin stemmer if there's interest in doing so.
